server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  quartz:
    job-store-type: JDBC #数据库存储quartz任务配置
    jdbc:
      initialize-schema: never #自动初始化表结构，第一次启动的时候这里写always

#mybatis:
#  mapper-locations: classpath:generator/*.xml

logging:
  config: classpath:log4j2-dev.xml
  level:
    com.example.demo: debug

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true