server:
  port: 8888
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 工作任务线程池，默认为io-threads的8倍
    worker-threads: 32

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:generator/*.xml

logging:
  level:
    com.example.demo: debug

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

context:
  listener:
    classes: com.example.demo.customlistener.MyListener3